/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.j4c62;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CloudEventGrpcServer {
  public static void main(String[] args) {
    SpringApplication.run(CloudEventGrpcServer.class, args);
  }
}
