/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.j4c62;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CloudEventGrpcServerTest {

}
